// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineService exposes engine/ algorithms to the Wails frontend.
 * Each exported method becomes an async callable in TypeScript via the
 * auto-generated bindings (run `make bindings` after adding methods).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "./engine/models.js";

/**
 * Triangulate runs Delaunay triangulation and returns a serialisable result.
 * The frontend receives triangles as flat index arrays ready for WebGL / Canvas.
 */
export function Triangulate(points: engine$0.Point[] | null): $CancellablePromise<engine$0.Mesh | null> {
    return $Call.ByID(1594089315, points);
}
