// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: polynav.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeometryService_Triangulate_FullMethodName = "/polynav.GeometryService/Triangulate"
	GeometryService_SaveMap_FullMethodName     = "/polynav.GeometryService/SaveMap"
)

// GeometryServiceClient is the client API for GeometryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Geometry and Path Planning Service
type GeometryServiceClient interface {
	// Perform Delaunay Triangulation on a set of points (obstacles)
	Triangulate(ctx context.Context, in *MapData, opts ...grpc.CallOption) (*TriangulationResult, error)
	// Persist map data to the database
	SaveMap(ctx context.Context, in *MapData, opts ...grpc.CallOption) (*SaveMapResponse, error)
}

type geometryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeometryServiceClient(cc grpc.ClientConnInterface) GeometryServiceClient {
	return &geometryServiceClient{cc}
}

func (c *geometryServiceClient) Triangulate(ctx context.Context, in *MapData, opts ...grpc.CallOption) (*TriangulationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriangulationResult)
	err := c.cc.Invoke(ctx, GeometryService_Triangulate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometryServiceClient) SaveMap(ctx context.Context, in *MapData, opts ...grpc.CallOption) (*SaveMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMapResponse)
	err := c.cc.Invoke(ctx, GeometryService_SaveMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeometryServiceServer is the server API for GeometryService service.
// All implementations must embed UnimplementedGeometryServiceServer
// for forward compatibility.
//
// Geometry and Path Planning Service
type GeometryServiceServer interface {
	// Perform Delaunay Triangulation on a set of points (obstacles)
	Triangulate(context.Context, *MapData) (*TriangulationResult, error)
	// Persist map data to the database
	SaveMap(context.Context, *MapData) (*SaveMapResponse, error)
	mustEmbedUnimplementedGeometryServiceServer()
}

// UnimplementedGeometryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeometryServiceServer struct{}

func (UnimplementedGeometryServiceServer) Triangulate(context.Context, *MapData) (*TriangulationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Triangulate not implemented")
}
func (UnimplementedGeometryServiceServer) SaveMap(context.Context, *MapData) (*SaveMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveMap not implemented")
}
func (UnimplementedGeometryServiceServer) mustEmbedUnimplementedGeometryServiceServer() {}
func (UnimplementedGeometryServiceServer) testEmbeddedByValue()                         {}

// UnsafeGeometryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeometryServiceServer will
// result in compilation errors.
type UnsafeGeometryServiceServer interface {
	mustEmbedUnimplementedGeometryServiceServer()
}

func RegisterGeometryServiceServer(s grpc.ServiceRegistrar, srv GeometryServiceServer) {
	// If the following call panics, it indicates UnimplementedGeometryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeometryService_ServiceDesc, srv)
}

func _GeometryService_Triangulate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometryServiceServer).Triangulate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometryService_Triangulate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometryServiceServer).Triangulate(ctx, req.(*MapData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometryService_SaveMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometryServiceServer).SaveMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometryService_SaveMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometryServiceServer).SaveMap(ctx, req.(*MapData))
	}
	return interceptor(ctx, in, info, handler)
}

// GeometryService_ServiceDesc is the grpc.ServiceDesc for GeometryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeometryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "polynav.GeometryService",
	HandlerType: (*GeometryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Triangulate",
			Handler:    _GeometryService_Triangulate_Handler,
		},
		{
			MethodName: "SaveMap",
			Handler:    _GeometryService_SaveMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "polynav.proto",
}
