// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: polynav.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Basic geometric point
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_polynav_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_polynav_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_polynav_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// An obstacle defined by a series of points (polygon)
type Obstacle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Obstacle) Reset() {
	*x = Obstacle{}
	mi := &file_polynav_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obstacle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obstacle) ProtoMessage() {}

func (x *Obstacle) ProtoReflect() protoreflect.Message {
	mi := &file_polynav_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obstacle.ProtoReflect.Descriptor instead.
func (*Obstacle) Descriptor() ([]byte, []int) {
	return file_polynav_proto_rawDescGZIP(), []int{1}
}

func (x *Obstacle) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

// Map data containing all obstacles and start/goal points
type MapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Obstacles     []*Obstacle            `protobuf:"bytes,1,rep,name=obstacles,proto3" json:"obstacles,omitempty"`
	Start         *Point                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Goal          *Point                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapData) Reset() {
	*x = MapData{}
	mi := &file_polynav_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_polynav_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_polynav_proto_rawDescGZIP(), []int{2}
}

func (x *MapData) GetObstacles() []*Obstacle {
	if x != nil {
		return x.Obstacles
	}
	return nil
}

func (x *MapData) GetStart() *Point {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *MapData) GetGoal() *Point {
	if x != nil {
		return x.Goal
	}
	return nil
}

// Result of a triangulation request
type Triangle struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	A                *Point                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B                *Point                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C                *Point                 `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	ConstrainedEdges []bool                 `protobuf:"varint,4,rep,packed,name=constrained_edges,json=constrainedEdges,proto3" json:"constrained_edges,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Triangle) Reset() {
	*x = Triangle{}
	mi := &file_polynav_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Triangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Triangle) ProtoMessage() {}

func (x *Triangle) ProtoReflect() protoreflect.Message {
	mi := &file_polynav_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Triangle.ProtoReflect.Descriptor instead.
func (*Triangle) Descriptor() ([]byte, []int) {
	return file_polynav_proto_rawDescGZIP(), []int{3}
}

func (x *Triangle) GetA() *Point {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *Triangle) GetB() *Point {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *Triangle) GetC() *Point {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *Triangle) GetConstrainedEdges() []bool {
	if x != nil {
		return x.ConstrainedEdges
	}
	return nil
}

type TriangulationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triangles     []*Triangle            `protobuf:"bytes,1,rep,name=triangles,proto3" json:"triangles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriangulationResult) Reset() {
	*x = TriangulationResult{}
	mi := &file_polynav_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriangulationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriangulationResult) ProtoMessage() {}

func (x *TriangulationResult) ProtoReflect() protoreflect.Message {
	mi := &file_polynav_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriangulationResult.ProtoReflect.Descriptor instead.
func (*TriangulationResult) Descriptor() ([]byte, []int) {
	return file_polynav_proto_rawDescGZIP(), []int{4}
}

func (x *TriangulationResult) GetTriangles() []*Triangle {
	if x != nil {
		return x.Triangles
	}
	return nil
}

type SaveMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MapId         string                 `protobuf:"bytes,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMapResponse) Reset() {
	*x = SaveMapResponse{}
	mi := &file_polynav_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMapResponse) ProtoMessage() {}

func (x *SaveMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polynav_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMapResponse.ProtoReflect.Descriptor instead.
func (*SaveMapResponse) Descriptor() ([]byte, []int) {
	return file_polynav_proto_rawDescGZIP(), []int{5}
}

func (x *SaveMapResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveMapResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveMapResponse) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

var File_polynav_proto protoreflect.FileDescriptor

const file_polynav_proto_rawDesc = "" +
	"\n" +
	"\rpolynav.proto\x12\apolynav\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"2\n" +
	"\bObstacle\x12&\n" +
	"\x06points\x18\x01 \x03(\v2\x0e.polynav.PointR\x06points\"\x84\x01\n" +
	"\aMapData\x12/\n" +
	"\tobstacles\x18\x01 \x03(\v2\x11.polynav.ObstacleR\tobstacles\x12$\n" +
	"\x05start\x18\x02 \x01(\v2\x0e.polynav.PointR\x05start\x12\"\n" +
	"\x04goal\x18\x03 \x01(\v2\x0e.polynav.PointR\x04goal\"d\n" +
	"\bTriangle\x12\x1c\n" +
	"\x01a\x18\x01 \x01(\v2\x0e.polynav.PointR\x01a\x12\x1c\n" +
	"\x01b\x18\x02 \x01(\v2\x0e.polynav.PointR\x01b\x12\x1c\n" +
	"\x01c\x18\x03 \x01(\v2\x0e.polynav.PointR\x01c\"F\n" +
	"\x13TriangulationResult\x12/\n" +
	"\ttriangles\x18\x01 \x03(\v2\x11.polynav.TriangleR\ttriangles\"\\\n" +
	"\x0fSaveMapResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\tR\x05mapId2\x87\x01\n" +
	"\x0fGeometryService\x12=\n" +
	"\vTriangulate\x12\x10.polynav.MapData\x1a\x1c.polynav.TriangulationResult\x125\n" +
	"\aSaveMap\x12\x10.polynav.MapData\x1a\x18.polynav.SaveMapResponseB.\n" +
	"\rfyp.generatedB\fPolyNavProtoP\x01Z\rpolynav/protob\x06proto3"

var (
	file_polynav_proto_rawDescOnce sync.Once
	file_polynav_proto_rawDescData []byte
)

func file_polynav_proto_rawDescGZIP() []byte {
	file_polynav_proto_rawDescOnce.Do(func() {
		file_polynav_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polynav_proto_rawDesc), len(file_polynav_proto_rawDesc)))
	})
	return file_polynav_proto_rawDescData
}

var file_polynav_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_polynav_proto_goTypes = []any{
	(*Point)(nil),               // 0: polynav.Point
	(*Obstacle)(nil),            // 1: polynav.Obstacle
	(*MapData)(nil),             // 2: polynav.MapData
	(*Triangle)(nil),            // 3: polynav.Triangle
	(*TriangulationResult)(nil), // 4: polynav.TriangulationResult
	(*SaveMapResponse)(nil),     // 5: polynav.SaveMapResponse
}
var file_polynav_proto_depIdxs = []int32{
	0,  // 0: polynav.Obstacle.points:type_name -> polynav.Point
	1,  // 1: polynav.MapData.obstacles:type_name -> polynav.Obstacle
	0,  // 2: polynav.MapData.start:type_name -> polynav.Point
	0,  // 3: polynav.MapData.goal:type_name -> polynav.Point
	0,  // 4: polynav.Triangle.a:type_name -> polynav.Point
	0,  // 5: polynav.Triangle.b:type_name -> polynav.Point
	0,  // 6: polynav.Triangle.c:type_name -> polynav.Point
	3,  // 7: polynav.TriangulationResult.triangles:type_name -> polynav.Triangle
	2,  // 8: polynav.GeometryService.Triangulate:input_type -> polynav.MapData
	2,  // 9: polynav.GeometryService.SaveMap:input_type -> polynav.MapData
	4,  // 10: polynav.GeometryService.Triangulate:output_type -> polynav.TriangulationResult
	5,  // 11: polynav.GeometryService.SaveMap:output_type -> polynav.SaveMapResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_polynav_proto_init() }
func file_polynav_proto_init() {
	if File_polynav_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polynav_proto_rawDesc), len(file_polynav_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polynav_proto_goTypes,
		DependencyIndexes: file_polynav_proto_depIdxs,
		MessageInfos:      file_polynav_proto_msgTypes,
	}.Build()
	File_polynav_proto = out.File
	file_polynav_proto_goTypes = nil
	file_polynav_proto_depIdxs = nil
}
