// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum EdgeID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    NoneEdge = -1,
};

/**
 * HalfEdge represents a directed edge of a triangle.
 */
export interface HalfEdge {
    /**
     * Point index where this edge starts
     */
    "Origin": VertexID;

    /**
     * The opposite half-edge (None if it's on the boundary/hull)
     */
    "Twin": EdgeID;

    /**
     * The next edge in the triangle CCW
     */
    "Next": EdgeID;

    /**
     * The triangle this half-edge belongs to
     */
    "Triangle": TriangleID;

    /**
     * Locked in CDT
     */
    "IsConstrained": boolean;
}

/**
 * Mesh is the complete output of a Delaunay triangulation.
 */
export interface Mesh {
    /**
     * Normalised input points
     */
    "Points": Point[] | null;

    /**
     * Flat array storing all directed edges
     */
    "HalfEdges": HalfEdge[] | null;

    /**
     * Flat array storing all triangles
     */
    "Triangles": Triangle[] | null;

    /**
     * The most recently inserted edge, or None
     */
    "LastInsertedEdge": EdgeID;
}

/**
 * Point represents a 2D coordinate.
 */
export interface Point {
    "X": number;
    "Y": number;
}

/**
 * Triangle references three points by their index in a point slice
 */
export interface Triangle {
    /**
     * One of the half-edges bounding this triangle
     */
    "Edge": EdgeID;

    /**
     * Marks this triangle as deleted
     */
    "Tombstoned": boolean;
}

export enum TriangleID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    NoneTriangle = -1,
};

export enum VertexID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    NoneVertex = -1,
};
