// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Edge connects two point indices. Undirected: (A,B) == (B,A).
 */
export interface Edge {
    "A": number;
    "B": number;
}

/**
 * Mesh is the complete output of a Delaunay triangulation.
 */
export interface Mesh {
    /**
     * normalised input points
     */
    "Points": Point[] | null;

    /**
     * flat triangle index buffer (3 per triangle)
     */
    "Indices": number[] | null;

    /**
     * unique edges (no duplicates, no interior diagonals doubled)
     */
    "Edges": Edge[] | null;

    /**
     * hull edges (edges belonging to only one triangle)
     */
    "Boundary": Edge[] | null;
}

/**
 * Point represents a 2D coordinate.
 */
export interface Point {
    "X": number;
    "Y": number;
}
